print ("Credits")
print ("\nIdea")
print ("Sean Patrick Myrick")
print ("\nPython programming")
print ("Sean Patrick Myrick")
print ("\nConnection.py")
print ("Sean Patrick Myrick")
print ("\nAbout.py")
print ("Sean Patrick Myrick")
print ("\nFAQ.py")
print ("Sean Patrick Myrick")
print ("\nUnicodetest.py")
print ("Sean Patrick Myrick")
print ("\nCredits.py")
print ("Sean Patrick Myrick")
print ("\nSpecial thanks to")
print ("Sean Patrick Myrick")
noMore = input("Press [ENTER] key to continue")