print ("Unicode testing for uDonate")
print ("\n")
print ("USD - $") # not unicode but it is a required symbol")
print ("US Coin - ¢") 
print ("Pound - £")
print ("Yen - ¥")
print ("Euro-Currency - ₠")
print ("Colon - ₡")
print ("Cruzeiro - ₢")
print ("French Franc - ₣")
print ("Lira - ₤")
print ("Mill - ₥")
print ("Naira - ₦")
print ("Won - ₩")
print ("New Sheqel - ₪")
print ("Dong - ₫")
print ("Euro - €")
print ("Kip - ₭")
print ("Tugrik - ₮")
print ("German penny - ₰")
print ("Peso - ₱")
print ("Guarani - ₲")
print ("Austral - ₳")
print ("Hryvnia - ₴")
print ("Cedi - ₵")
print ("Spesmilo - ₷")
noMore = input("Press [ENTER] key to quit")